// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Provides AI-powered suggestions for plan names based on plan details.
 *
 * - suggestPlanName - A function that suggests plan names.
 * - SuggestPlanNameInput - The input type for the suggestPlanName function.
 * - SuggestPlanNameOutput - The return type for the suggestPlanName function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestPlanNameInputSchema = z.object({
  description: z.string().describe('The description of the plan.'),
  eventDateTime: z.string().describe('The date and time of the event.'),
  city: z.string().describe('The city where the event is taking place.'),
  eventType: z.string().describe('The type of event (e.g., concert, dinner, party).'),
});
export type SuggestPlanNameInput = z.infer<typeof SuggestPlanNameInputSchema>;

const SuggestPlanNameOutputSchema = z.object({
  planName: z.string().describe('A suggested name for the plan.'),
});
export type SuggestPlanNameOutput = z.infer<typeof SuggestPlanNameOutputSchema>;

export async function suggestPlanName(input: SuggestPlanNameInput): Promise<SuggestPlanNameOutput> {
  return suggestPlanNameFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestPlanNamePrompt',
  input: {schema: SuggestPlanNameInputSchema},
  output: {schema: SuggestPlanNameOutputSchema},
  prompt: `Suggest a creative and relevant name for a plan, based on the following details:

Description: {{{description}}}
Event Date/Time: {{{eventDateTime}}}
City: {{{city}}}
Event Type: {{{eventType}}}

Give only the name of the plan. Do not use any punctuation. Make it short and memorable. The plan name must be in title case.`,
});

const suggestPlanNameFlow = ai.defineFlow(
  {
    name: 'suggestPlanNameFlow',
    inputSchema: SuggestPlanNameInputSchema,
    outputSchema: SuggestPlanNameOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
